### ISSUE TITLE
aplySchema crashes with empy field of params

### ISSUE THREAD

**Issue by joanvallve** [joanvallve/yaml-schema-cpp#2]
(copied from gitlab. Author: @PepMS)

I have the following situation, where I have a non-mandatory with default `param_1` specified inside a `params` family. That is,
```yaml
params:
    param_1:
      _mandatory: false
      _type: string
      _doc: "doc_1"
      _default: "string_1"
```
If, in the input `yaml` file we do not specify (at least) the `params:` field, the `applySchema()` breaks. Probably it is because it tries to access the `node[`params`] to apply the default of `param_1` but it does not exist.

I think that a good solution for this might be to add the family node name (in this case `params`) if it does not exist in the input yaml.
