### ISSUE TITLE
allow empty schemas

### ISSUE THREAD

**Issue by joanvallve** [joanvallve/yaml-schema-cpp#4]
(copied from Gitlab. Author: @PepMS )

I found the case where I have a base class that requires no parameters or data to be introduced. Thus, its schema is empty.

Still, I'd like to have an empty base schema, which is not allowed now. 

Eventually, the base class might have need some parameters and then, I'll have the machinery ready to add these in the empty base schema.

A workaround is to add in the base class a dummy parameter:
```yaml
dummy:
  mandatory: false
  type: double
  default: 0
  doc: ""
```
